# Generated by Django 5.2 on 2025-07-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_key', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('suporte', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('problema', models.TextField(blank=True, null=True)),
                ('indicador', models.CharField(blank=True, max_length=100, null=True)),
                ('tempo_solucao', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WhatsAppNote',
        ),
    ]
