# Generated by Django 5.2 on 2025-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0002_whatsappslot_delete_whatsappnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappslot',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
