# Generated by Django 5.2 on 2025-07-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0003_whatsappslot_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappslot',
            name='chamadofinalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappslot',
            name='codigo_chamado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
