# Generated by Django 5.2 on 2025-07-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0004_whatsappslot_chamadofinalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappslot',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
    ]
