# Generated by Django 5.2.4 on 2025-07-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0005_whatsappslot_deletado'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappslot',
            name='chamadoaberto',
            field=models.BooleanField(default=False),
        ),
    ]
