# Generated by Django 5.2.4 on 2025-07-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0006_whatsappslot_chamadoaberto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappslot',
            name='chamadoaberto',
        ),
    ]
