# Generated by Django 5.2.4 on 2025-07-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0009_alter_whatsappslot_suporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappslot',
            name='suporte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
