# Generated by Django 5.2.4 on 2025-07-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0010_alter_whatsappslot_suporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappslot',
            name='resumo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
