# Generated by Django 5.2.4 on 2025-07-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0011_whatsappslot_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappslot',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappslot',
            name='solucao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
