# Generated by Django 5.2.4 on 2025-07-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0012_whatsappslot_setor_whatsappslot_solucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(help_text='Número no formato DDI+DDD+Número, ex: 5514912345678', max_length=20, unique=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
