# Generated by Django 5.2.4 on 2025-08-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0014_cliente_delete_registeredclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappslot',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp_media/'),
        ),
        migrations.AddField(
            model_name='whatsappslot',
            name='msg_type',
            field=models.CharField(default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsappslot',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
