# Generated by Django 5.2.4 on 2025-08-03 01:43

import Noc.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noc', '0015_whatsappslot_media_file_whatsappslot_msg_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappslot',
            name='codigo_chamado',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_chamado', models.CharField(db_index=True, max_length=100)),
                ('texto', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=Noc.models.observacao_media_path)),
                ('msg_type', models.CharField(default='text', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
